### ISSUE TITLE
[Question] New Docker deployment

### ISSUE THREAD

**Issue by simon-jouet** [polonel/trudesk#197]
Hi,

First off, thanks @polonel for the work on trudesk, I just came across it but it seems very promising.

I'm running into some troubles getting it up and running though, I'm sure I'm missing something but I tried to follow the available documentation and opened issues. I can get through the install fine and start configuring things up.

**Current setup:**
- I was running version 1.0.11 but ran into the same issue as described in !192 so I reverted to 1.0.10 for now.
- My setup is running in a docker swarm cluster (see below for my current stack definition - this will move to kubernetes at some point but it's not important)
- I've followed the trudesk instructions from https://hub.docker.com/r/polonel/trudesk

**Issues:**
So I'm running into the following problems:
- Every time the stack is removed and restarted i need to go through the config again. I've followed the docker instructions on which folders to persist in docker but maybe it's something not yet in the docker hub config?
- I can't seem to get the Mail checker to work, I'm using Gmail's IMAP with a fairly out the box config (see image below), I send an email to the mailbox but even if i wait a poll period I don't see any new issue. (I made sure the server was restarted after enabling the mailer check) (the username has been redacted in the image below)
![image](https://user-images.githubusercontent.com/832495/57223209-39e18200-6ffd-11e9-90ae-24176a256508.png)
- To debug the point above I tried to check the logs but when I check in `/settings/logs` I get the message `Invalid Log File...`
![image](https://user-images.githubusercontent.com/832495/57223275-6e553e00-6ffd-11e9-9c82-09a24f17130e.png)
- I might have missed it but it there a way to restart trudesk through the admin panel? I wanted to finish configuring the mail checker before restarting but once everything was filled I couldn't reboot, so I disabled and reenable the mailer check.

**Stack**
```yml
version: '3.7'

services:
  trudesk:
    image: polonel/trudesk:1.0.10
    environment:
      - NODE_ENV=production
      - TRUDESK_DOCKER=true
      - TD_MONGODB_SERVER=mongodb
      - TD_MONGODB_DATABASE=trudesk
    networks:
      - mongo
      - proxy
    volumes:
      - trudesk-uploads:/usr/src/trudesk/public/uploads
      - trudesk-plugins:/usr/src/trudesk/plugins
      - trudesk-backups:/usr/src/trudesk/backups
    deploy:
      placement:
        constraints: [node.labels.trudesk == true]
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=<domain>
        - com.df.httpsOnly=true
        - com.df.port=8118
        - com.df.letsencrypt.host=<domain>
        - com.df.letsencrypt.email=<email>

networks:
  mongo:
    name: databases
    external: true
  proxy:
    name: proxy
    external: true    

# Persistent volume between service instantiations
volumes:
  trudesk-uploads:
  trudesk-plugins:
  trudesk-backups:
```
