### ISSUE TITLE
Improve docker-compose for DNS

### ISSUE THREAD

**Issue by Gill-Bates** [polonel/trudesk#471]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

In the current version of the `docker-compose.yml`, DNS will not resolve the URL to my Mailserver.

Adding a DNS-Resolver to the network properties will solve this issue:

```
version: '3'
services:
  trudesk:
    image: polonel/trudesk:1
    restart: always
    ports:
      - "9090:8118"
    dns:
      - "9.9.9.9"
      - "149.112.112.112"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
networks:
  default:
volumes:
  mongo:
```
