### ISSUE TITLE
Empty email body when ticket-comment-added

### ISSUE THREAD

**Issue by geeeksameer** [polonel/trudesk#480]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Email body is empty when new comment is added on the ticket, email body just have the titles like:

Updated:
Ticket Group:
Ticket Submitted by:
Submitted Date:
Ticket Type:
Ticket Priority:
Tags:

Ticket Issue

Comments

**What did you expect to happen**:
All these labels should have values in the email.

**How to reproduce it (as minimally and precisely as possible)**:
Add comment to the ticket

**Anything else we need to know?**:

**Environment**: 
- Trudesk Version: 1.1.11
- OS (e.g. from /etc/os-release): Ubuntu
- Node.JS Version: 12.9.0
- MongoDB Version: 4.4.12 Enterprise
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Can you confirm if this is with the new "Beta Email Templates" or is the new templates disabled?

**Comment by geeeksameer** [comment]
![image](https://user-images.githubusercontent.com/64781959/155552096-9a606615-a326-40e6-9594-19ce8e483ced.png)

**Comment by geeeksameer** [comment]
I tried it with above option disabled but the update email is still empty, but the ticket creation email looks fine, I am attaching more screenshots below.

**Comment by geeeksameer** [comment]
![image](https://user-images.githubusercontent.com/64781959/155559024-606aefc6-a8df-407f-a6af-96221d3c6eb2.png)

**Comment by geeeksameer** [comment]
Ticket creation email to assignee

![image](https://user-images.githubusercontent.com/64781959/155559369-70543a75-382a-49da-a918-a507e365c27e.png)

**Comment by geeeksameer** [comment]
Account details email to new requester 
Username missing in this one, password is fine present in the email...

![image](https://user-images.githubusercontent.com/64781959/155560760-55db2ed2-a261-411d-bc9c-954686cb2255.png)

**Comment by polonel** [comment]
Thanks for the screenshots and info. I'm looking into the issue.

**Comment by geeeksameer** [comment]
I appreciate your efforts and looking into this.
I am looking forward to solution!

**Comment by geeeksameer** [comment]
This fix certainly worked.
Great work man.

I really appreciate your efforts, you're doing tremendous job.

**Comment by Gill-Bates** [comment]
What’s the solution?

**Comment by geeeksameer** [comment]
> What’s the solution?

Click ⬇️ This is plug-n-play solution here, come on:

https://github.com/polonel/trudesk/commit/cd5463166d586ec31f816984fe5e28c90712f6fe

**Comment by suprematis** [comment]
I ran into the same issue while using version 1.1.8.  I changed my docker-compose.yml file to use the latest image posted at Docker Hub [polonel/trudesk](https://hub.docker.com/r/polonel/trudesk/tags) and it fixed the issue.  Now all customers are getting emails with all the correct and complete content.

```
version: '2.1'
services:
  trudesk:
    image: polonel/trudesk:latest
    restart: always
    ports:
      - "8118:8118"
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"
    volumes:
      - trudesk_uploads:/usr/src/trudesk/public/uploads
      - trudesk_backups:/usr/src/trudesk/backups
  mongo:
    image: mongo:5.0-focal
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
      - mongo_data:/data/db:rw
  elasticsearch:
    image: elasticsearch:8.0.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
volumes:
  trudesk_uploads:
  trudesk_backups:
  mongo:
  mongo_data:
  elasticsearch:
```
