### ISSUE TITLE
Example docker compose does not persist data

### ISSUE THREAD

**Issue by jrj2211** [polonel/trudesk#517]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Using the example docker compose script, if the docker containers get recreated the mongo data volume is not persisted causing all data to be lost.

**What did you expect to happen**:
Example should be configured to persist data. Someone new to docker may not know this, start adding a bunch of tickets and upon restarting lose all their data.

**How to fix it**:

The /data/db folder needs to be a named or external mount. Add the following lines to the example for volumes:

```
version: '3.7'
services:
  mongo:
    image: mongo:5.0-focal
    volumes:
      - mongo:/var/lib/mongo
      - mongo_data:/data/db:rw
volumes:
  mongo_data:
```

**Environment**:
- Trudesk Version: 1.2.4
- OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- Node.JS Version: From docker image
- MongoDB Version: 5.0-focal
- Is this hosted on cloud.trudesk.io: No
